data_loader:
  name: TOWIDS
  number_of_bytes: 58
  protocol_filter: IP_UDP
  raw_x_path: data/tow-ids-dataset/raw/Automotive_Ethernet_with_Attack_original_10_17_20_04_test.pcap
  raw_y_path: data/tow-ids-dataset/raw/y_test.csv
  test_raw_x_path: data/tow-ids-dataset/raw/Automotive_Ethernet_with_Attack_original_10_17_20_04_test.pcap
  test_raw_y_path: data/tow-ids-dataset/raw/y_test.csv
metrics:
  name: ae
modeling:
  inference:
    batch_size: 64
    name: pred
    target_label: CAN DoS
  structure:
    T: 2
    dropout: 0.2
    final_layer: true
    hidden_size: 40
    input_size: 13
    kernel_size: 3
    mlp: false
    name: tcn_pred
    num_levels: 4
    sig: false
  training:
    batch_size: 16
    clip: 0.2
    criterion: mean_squared_error
    es_delta: 0.0001
    es_patience: 10
    learning_rate: 0.001
    name: pred
    num_epochs: 250
phase: train
pre_processing:
  jump_bytes: 34
  name: sliding-window
  number_payload_bytes: 16
  processed_path: data/tow-ids-dataset/processed
  save_batch_size: 10000
  window_size: 64
  window_stride: 16
run_id: our_UDP
tracker:
  name: null
  project: w_sizes-fixed_params
