phase: train

tracker:
  name: 
  project: cae_lstmae_dev

data_loader:
  name: AEID
  raw_x_path: data/autoeth-intrusion-dataset/raw/driving_02_injected.pcap
  injected_path: data/autoeth-intrusion-dataset/raw/single-MPEG-frame.pcap
  number_of_bytes: 58

pre_processing:
  name: sliding-window
  processed_path: data/autoeth-intrusion-dataset/processed
  window_size: 40
  window_stride: 16
  save_batch_size: 10000

modeling:
  structure:
    name: cae
    in_channels: 40
    input_size: 58
    num_levels: 3
    hidden_size: 40
  
  training:
    name: ae
    criterion: mean_squared_error
    learning_rate: 0.0001
    num_epochs: 250
    es_patience: 5
    es_delta: 0.0001
    batch_size: 16

  inference:
    name: ae
    batch_size: 64

metrics:
  name: natasha_ae
  alpha: 0.5
