phase: train

tracker:
  name: 
  project: tcn_pred_dev

data_loader:
  name: TOWIDS
  raw_x_path: data/tow-ids-dataset/raw/Automotive_Ethernet_with_Attack_original_10_17_19_50_training.pcap
  raw_y_path: data/tow-ids-dataset/raw/y_train.csv
  number_of_bytes: 58

pre_processing:
  name: sliding-window
  processed_path: data/tow-ids-dataset/processed
  window_size: 4
  window_stride: 1
  save_subset: 0.1

modeling:
  structure:
    name: cae
    in_channels: 4
    input_size: 58
    num_levels: 1
    hidden_size: 64
  
  training:
    name: ae
    criterion: mean_squared_error
    learning_rate: 0.0001
    num_epochs: 1
    es_patience: 5
    batch_size: 16

  inference:
    name: ae
    batch_size: 64

metrics:
  name: anomaly_detector
