data_loader:
  injected_path: data/autoeth-intrusion-dataset/raw/single-MPEG-frame.pcap
  name: AEID
  number_of_bytes: 58
  raw_x_path: data/autoeth-intrusion-dataset/raw/driving_01_injected.pcap
  raw_y_path: null
  test_raw_x_path: data/autoeth-intrusion-dataset/raw/driving_01_injected.pcap
metrics:
  alpha: 0.5
  name: natasha_ae
modeling:
  inference:
    batch_size: 64
    name: ae
  structure:
    hidden_size: 10
    input_size: 58
    name: lstmae
  training:
    batch_size: 16
    criterion: mean_squared_error
    es_delta: 0.0001
    es_patience: 5
    learning_rate: 0.0001
    name: ae
    num_epochs: 250
phase: train
pre_processing:
  name: sliding-window
  processed_path: data/autoeth-intrusion-dataset/processed
  save_batch_size: 10000
  window_size: 40
  window_stride: 16
run_id: lstmae_AEID_20260127_191616
tracker:
  name: null
  project: cae_lstmae_dev
